In [1]:
import numpy as np

from bokeh.models import ColumnDataSource, DataRange1d, Plot, LinearAxis, Grid
from bokeh.models.glyphs import MultiLine
from bokeh.io import curdoc, show

N = 9
x = np.linspace(-2, 2, N)
y = x**2

xpts = np.array([-.09, -.12, .0, .12,  .09])
ypts = np.array([-.1,   .02, .1, .02, -.1])

source = ColumnDataSource(dict(
        xs=[xpts*(1+i/10.0)+xx for i, xx in enumerate(x)],
        ys=[ypts*(1+i/10.0)+yy for i, yy in enumerate(y)],
    )
)

xdr = DataRange1d()
ydr = DataRange1d()

plot = Plot(
    title=None, x_range=xdr, y_range=ydr, plot_width=300, plot_height=300,
    h_symmetry=False, v_symmetry=False, min_border=0, toolbar_location=None)

glyph = MultiLine(xs="xs", ys="ys", line_color="#8073ac", line_width=2)
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)

show(plot)

In [4]:
source.data

{'xs': [array([-2.09, -2.12, -2.  , -1.88, -1.91]),
  array([-1.599, -1.632, -1.5  , -1.368, -1.401]),
  array([-1.108, -1.144, -1.   , -0.856, -0.892]),
  array([-0.617, -0.656, -0.5  , -0.344, -0.383]),
  array([-0.126, -0.168,  0.   ,  0.168,  0.126]),
  array([ 0.365,  0.32 ,  0.5  ,  0.68 ,  0.635]),
  array([ 0.856,  0.808,  1.   ,  1.192,  1.144]),
  array([ 1.347,  1.296,  1.5  ,  1.704,  1.653]),
  array([ 1.838,  1.784,  2.   ,  2.216,  2.162])],
 'ys': [array([ 3.9 ,  4.02,  4.1 ,  4.02,  3.9 ]),
  array([ 2.14 ,  2.272,  2.36 ,  2.272,  2.14 ]),
  array([ 0.88 ,  1.024,  1.12 ,  1.024,  0.88 ]),
  array([ 0.12 ,  0.276,  0.38 ,  0.276,  0.12 ]),
  array([-0.14 ,  0.028,  0.14 ,  0.028, -0.14 ]),
  array([ 0.1 ,  0.28,  0.4 ,  0.28,  0.1 ]),
  array([ 0.84 ,  1.032,  1.16 ,  1.032,  0.84 ]),
  array([ 2.08 ,  2.284,  2.42 ,  2.284,  2.08 ]),
  array([ 3.82 ,  4.036,  4.18 ,  4.036,  3.82 ])]}